"""Canonical machine-readable reason codes shared across components."""

from enum import StrEnum


class ReasonFamily(StrEnum):
    """Recognized reason-code namespaces."""

    BROKER = "BROKER"
    CONTROL = "CONTROL"
    DATA = "DATA"
    EXPOSURE = "EXPOSURE"
    KILL = "KILL"
    LOSS = "LOSS"
    MODE = "MODE"
    ORDER = "ORDER"
    RECON = "RECON"
    REPORT = "REPORT"
    RISK = "RISK"
    SECURITY = "SECURITY"
    STATE = "STATE"
    TIME = "TIME"


class ReasonCode(StrEnum):
    """Stable reason values; member names may evolve, values may not."""

    CONFIG_MISSING = "MODE_CONFIG_MISSING"
    CONFIG_INVALID = "MODE_CONFIG_INVALID"
    LIVE_DENIED = "MODE_LIVE_DENIED"
    PAPER_VERIFIED = "MODE_PAPER_VERIFIED"
    MODE_NOT_RUNNING = "MODE_NOT_RUNNING"

    DATA_FUTURE = "DATA_FUTURE"
    DATA_STALE = "DATA_STALE"
    LIQUIDITY_MISSING = "DATA_LIQUIDITY_MISSING"
    DATA_REVISION_DETECTED = "DATA_REVISION_DETECTED"

    CLOCK_OFFSET = "TIME_CLOCK_OFFSET"
    SESSION_CLOSED = "TIME_SESSION_CLOSED"
    INTENT_IN_FUTURE = "TIME_INTENT_IN_FUTURE"

    RISK_APPROVED = "RISK_APPROVED"
    RISK_INPUT_MISSING = "STATE_RISK_INPUT_MISSING"
    NOT_RECONCILED = "STATE_NOT_RECONCILED"
    UNKNOWN_ORDER = "STATE_UNKNOWN_ORDER"

    SYMBOL_NOT_ALLOWED = "ORDER_SYMBOL_NOT_ALLOWED"
    ORDER_TYPE_NOT_ALLOWED = "ORDER_TYPE_NOT_ALLOWED"
    TIME_IN_FORCE_NOT_ALLOWED = "ORDER_TIME_IN_FORCE_NOT_ALLOWED"
    ORDER_QUANTITY_LIMIT = "ORDER_QUANTITY_LIMIT"
    ORDER_NOTIONAL_LIMIT = "ORDER_NOTIONAL_LIMIT"
    ORDER_ACCEPTED = "ORDER_ACCEPTED"
    ORDER_OUTCOME_UNKNOWN = "ORDER_OUTCOME_UNKNOWN"

    SHORT_NOT_ALLOWED = "EXPOSURE_SHORT_NOT_ALLOWED"
    POSITION_NOTIONAL_LIMIT = "EXPOSURE_POSITION_NOTIONAL_LIMIT"
    POSITION_CONCENTRATION_LIMIT = "EXPOSURE_POSITION_CONCENTRATION_LIMIT"
    GROSS_EXPOSURE_LIMIT = "EXPOSURE_GROSS_LIMIT"
    NET_EXPOSURE_LIMIT = "EXPOSURE_NET_LIMIT"
    LEVERAGE_LIMIT = "EXPOSURE_LEVERAGE_LIMIT"
    OPEN_POSITIONS_LIMIT = "EXPOSURE_OPEN_POSITIONS_LIMIT"
    ADV_LIMIT = "EXPOSURE_ADV_LIMIT"

    INTERNAL_HALT = "KILL_INTERNAL_HALT"
    OPERATOR_KILL = "KILL_OPERATOR_CONTROL"
    KILL_CLEAR = "CONTROL_KILL_CLEAR"
    KILL_UNKNOWN = "CONTROL_KILL_UNKNOWN"
    KILL_PRESENT = "CONTROL_KILL_PRESENT"
    WATCHDOG_UNHEALTHY = "CONTROL_WATCHDOG_UNHEALTHY"
    ORDER_RATE_LIMIT = "CONTROL_ORDER_RATE_LIMIT"
    HEARTBEAT_MISSING = "CONTROL_HEARTBEAT_MISSING"
    HEARTBEAT_UNREADABLE = "CONTROL_HEARTBEAT_UNREADABLE"
    HEARTBEAT_INVALID = "CONTROL_HEARTBEAT_INVALID"
    HEARTBEAT_FUTURE = "CONTROL_HEARTBEAT_FUTURE"
    HEARTBEAT_STALE = "CONTROL_HEARTBEAT_STALE"
    HEARTBEAT_HEALTHY = "CONTROL_HEARTBEAT_HEALTHY"
    HEARTBEAT_LOST = "CONTROL_HEARTBEAT_LOST"

    DAILY_LOSS_LIMIT = "LOSS_DAILY_LIMIT"
    DRAWDOWN_LIMIT = "LOSS_DRAWDOWN_LIMIT"

    RECON_POSITION_MISMATCH = "RECON_POSITION_MISMATCH"
    RECON_PASSED = "RECON_PASSED"
    BROKER_DISCONNECTED = "BROKER_DISCONNECTED"
    BROKER_THROTTLED = "BROKER_THROTTLED"
    SECURITY_REDACTION_FAILURE = "SECURITY_REDACTION_FAILURE"
    SECURITY_ACCOUNT_MISMATCH = "SECURITY_ACCOUNT_MISMATCH"
    REPORT_NO_TRADE = "REPORT_NO_TRADE"
    REPORT_DELIVERY_FAILED = "REPORT_DELIVERY_FAILED"

    @property
    def family(self) -> ReasonFamily:
        """Return the namespace encoded before the first underscore."""

        return ReasonFamily(self.value.partition("_")[0])
